export { default as navigation } from "./navigation";

export const GENRES = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Fantasy",
  "Horror",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Slice of Life",
  "Sports",
  "Supernatural",
  "Thriller",
  "Mecha",
  "Music",
  "Psychological",
];

export const SAMPLE_ANIME = [
  {
    id: 1,
    title: "Attack on Titan",
    titleJapanese: "進撃の巨人",
    slug: "attack-on-titan",
    coverImage: "/images/aot.jpg",
    rating: 9.0,
    year: 2013,
    status: "Completed",
    episodes: 87,
    genres: ["Action", "Drama", "Fantasy"],
    studio: "MAPPA",
  },
  {
    id: 2,
    title: "Demon Slayer",
    titleJapanese: "鬼滅の刃",
    slug: "demon-slayer",
    coverImage: "/images/ds.jpg",
    rating: 8.7,
    year: 2019,
    status: "Ongoing",
    episodes: 44,
    genres: ["Action", "Supernatural"],
    studio: "ufotable",
  },
  {
    id: 3,
    title: "Jujutsu Kaisen",
    titleJapanese: "呪術廻戦",
    slug: "jujutsu-kaisen",
    coverImage: "/images/jjk.jpg",
    rating: 8.8,
    year: 2020,
    status: "Ongoing",
    episodes: 47,
    genres: ["Action", "Supernatural"],
    studio: "MAPPA",
  },
  {
    id: 4,
    title: "One Piece",
    titleJapanese: "ワンピース",
    slug: "one-piece",
    coverImage: "/images/op.jpg",
    rating: 8.9,
    year: 1999,
    status: "Ongoing",
    episodes: 1100,
    genres: ["Action", "Adventure", "Comedy"],
    studio: "Toei Animation",
  },
  {
    id: 5,
    title: "Spy x Family",
    titleJapanese: "スパイファミリー",
    slug: "spy-x-family",
    coverImage: "/images/sxf.jpg",
    rating: 8.5,
    year: 2022,
    status: "Ongoing",
    episodes: 37,
    genres: ["Action", "Comedy", "Slice of Life"],
    studio: "WIT Studio",
  },
];
